on:
  push:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
      - uses: ./.github/actions/reproduce-composite
      - uses: ./.github/actions/reproduce-docker-file
      - uses: ./.github/actions/reproduce-docker-path
